# Generated by Django 3.2.3 on 2021-06-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0003_alter_safe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='site_password',
            field=models.CharField(max_length=300),
        ),
    ]
