# Generated by Django 3.2.3 on 2021-06-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='master_key',
            field=models.CharField(default='', max_length=128),
        ),
    ]
