# Generated by Django 3.2.3 on 2021-06-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_master_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='master_key',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
