# Generated by Django 3.2.3 on 2021-06-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_master_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='master_key',
        ),
    ]
